name: 'nf26_smart_teem'
version: '1.0.0'
profile: 'nf26_smart_teem'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nf26_smart_teem:
    wrk:
      +materialized: table
      +schema: WRK
    soc:
      +materialized: table
      +schema: SOC
