name: "nf26_hospital"
version: "1.0.0"
profile: "nf26_hospital"

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"
  - "logs"

on-run-start:
  - "{{ log_run_start() }}"
on-run-end:
  - "{{ log_run_end() }}"

models:
  nf26_hospital:
    +pre_hook:
      - "{{ log_exec_start(this.name) }}"
    +post_hook:
      - "{{ log_exec_end(this.name, 'OK') }}"
    wrk:
      +materialized: table
      +schema: WRK
    soc:
      +schema: SOC
      +materialized: table     
      R_PART:
        +materialized: incremental
        +unique_key: ['SRC_ID', 'SRC_TYP']
      O_INDV:
        +materialized: incremental
        +unique_key: PART_ID
      O_CONS:
        +materialized: incremental
        +unique_key: CONS_ID
      O_HOSP:
        +materialized: incremental
        +unique_key: HOSP_ID
      O_TRET:
        +materialized: incremental
        +unique_key: TRET_ID
      O_ADDR:
        +materialized: incremental
        +unique_key: ['PART_ID', 'STRT_VALD_DTTM']
      O_TELP:
        +materialized: incremental
        +unique_key: ['PART_ID', 'STRT_VALD_DTTM']