version: 2

models:
  - name: wrk_room
    description: "Nettoyage et validation des chambres depuis STG"
  - name: wrk_medicine
    description: "Nettoyage et validation des médicaments depuis STG"
  - name: wrk_party
    description: "Unification personnel et patients depuis STG"
  - name: R_ROOM
    description: "Table de référence des chambres"
  - name: R_MEDC
    description: "Table de référence des médicaments avec surrogate key"
  - name: R_PART
    description: "Table de référence des tiers (personnel + patients) avec surrogate key"
