name: 'nf26_hospital'
version: '1.0.0'
config-version: 2

profile: 'nf26_hospital'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

# Hooks au niveau RUN : 1 ligne dans TCH.T_SUIV_RUN par exécution dbt
on-run-start:
  - "{{ log_run_start() }}"
on-run-end:
  - "{{ log_run_end() }}"

# Hooks au niveau MODEL : 1 ligne dans TCH.T_SUIV_TRMT par model
models:
  nf26_hospital:
    +pre_hook:
      - "{{ log_exec_start(this.name) }}"
    +post_hook:
      - "{{ log_exec_end(this.name, 'OK') }}"
    socle:
      +materialized: table
      +schema: SOC

