WITH cons AS (
    SELECT * FROM {{ ref('O_CONS') }}
),
indiv AS (
    SELECT * FROM {{ ref('O_INDV') }}
)
SELECT
    DATE(c.CONS_STRT_DTTM) AS JOUR,
    c.PATH_DSC AS PATHOLOGIE,
    COUNT(DISTINCT c.PATN_ID) AS NB_PATIENTS,
    AVG(DATEDIFF('YEAR', i.BIRT_DT, c.CONS_STRT_DTTM)) AS AGE_MOYEN
FROM cons c
INNER JOIN indiv i ON c.PATN_ID = i.PART_ID
WHERE c.PATH_DSC IS NOT NULL
  AND i.BIRT_DT IS NOT NULL
GROUP BY 1, 2
ORDER BY 1, 2

