WITH hosp AS (
    SELECT * FROM {{ ref('O_HOSP') }}
),
rooms AS (
    SELECT * FROM {{ ref('R_ROOM') }}
),
hosp_detail AS (
    SELECT
        DATE(h.HOSP_STRT_DTTM) AS JOUR,
        h.HOSP_ID,
        h.CONS_ID,
        h.STFF_ID,
        h.ROOM_NUM,
        h.HOSP_FINL_RATE,
        DATEDIFF('DAY', h.HOSP_STRT_DTTM, h.HOSP_END_DTTM) AS DUREE_JOURS,
        CASE WHEN DATEDIFF('DAY', h.HOSP_STRT_DTTM, h.HOSP_END_DTTM) >= 1 THEN 1 ELSE 0 END AS AU_MOINS_1_NUIT
    FROM hosp h
)
SELECT
    hd.JOUR,
    COUNT(DISTINCT hd.HOSP_ID) AS NB_HOSPITALISATIONS,
    COUNT(DISTINCT hd.CONS_ID) AS NB_CONSULTATIONS_LIEES,
    COUNT(DISTINCT hd.STFF_ID) AS NB_MEDECINS_RESPONSABLES,
    AVG(hd.DUREE_JOURS) AS DUREE_MOYENNE_JOURS,
    SUM(hd.HOSP_FINL_RATE) AS COUT_TOTAL,
    AVG(hd.HOSP_FINL_RATE) AS COUT_MOYEN,
    COUNT(DISTINCT hd.ROOM_NUM) AS NB_CHAMBRES_UTILISEES,
    SUM(hd.AU_MOINS_1_NUIT) AS NB_PATIENTS_AU_MOINS_1_NUIT,
    ROUND(SUM(hd.AU_MOINS_1_NUIT) * 100.0 / NULLIF(COUNT(DISTINCT hd.HOSP_ID), 0), 2) AS PCT_PATIENTS_1_NUIT_PLUS
FROM hosp_detail hd
GROUP BY 1
ORDER BY 1
