WITH cons AS (
    SELECT * FROM {{ ref('O_CONS') }}
),
tret AS (
    SELECT * FROM {{ ref('O_TRET') }}
),
medc AS (
    SELECT * FROM {{ ref('R_MEDC') }}
)
SELECT
    DATE(c.CONS_STRT_DTTM) AS JOUR,
    c.PATH_DSC AS PATHOLOGIE,
    m.MEDC_NAME AS NOM_MEDICAMENT,
    m.MEDC_CATG AS CATEGORIE_MEDICAMENT,
    m.MANF_BRND AS MARQUE,
    SUM(t.MEDC_QTY) AS QTE_TOTALE,
    COUNT(DISTINCT t.TRET_ID) AS NB_PRESCRIPTIONS,
    RANK() OVER (
        PARTITION BY DATE(c.CONS_STRT_DTTM), c.PATH_DSC
        ORDER BY SUM(t.MEDC_QTY) DESC
    ) AS RANG_QTE
FROM cons c
INNER JOIN tret t ON c.CONS_ID = t.CONS_ID
INNER JOIN medc m ON t.MEDC_ID = m.MEDC_ID
WHERE c.PATH_DSC IS NOT NULL
GROUP BY 1, 2, 3, 4, 5
ORDER BY 1, 2, QTE_TOTALE DESC
