WITH cons AS (
    SELECT * FROM {{ ref('O_CONS') }}
),
hosp AS (
    SELECT * FROM {{ ref('O_HOSP') }}
)
SELECT
    DATE(c.CONS_STRT_DTTM) AS JOUR,
    c.PATH_DSC AS PATHOLOGIE,
    COUNT(DISTINCT h.ROOM_NUM) AS NB_CHAMBRES_UTILISEES
FROM cons c
INNER JOIN hosp h ON c.CONS_ID = h.CONS_ID
WHERE c.PATH_DSC IS NOT NULL
GROUP BY 1, 2
ORDER BY 1, 2
