CREATE DATABASE IF NOT EXISTS STG;
CREATE DATABASE IF NOT EXISTS WRK;
CREATE DATABASE IF NOT EXISTS SOC;
CREATE DATABASE IF NOT EXISTS TCH;

CREATE SCHEMA IF NOT EXISTS STG.PUBLIC;
CREATE SCHEMA IF NOT EXISTS WRK.PUBLIC;
CREATE SCHEMA IF NOT EXISTS SOC.PUBLIC;
CREATE SCHEMA IF NOT EXISTS TCH.PUBLIC;