-- =============================================================
-- Script      : 02_create_tables_soc.sql
-- Description : Creation des tables de la zone Socle (SOC)
-- Date        : 2026-05-29
-- Note        : Idempotent — CREATE IF NOT EXISTS (dipao 5 TD1)
-- =============================================================

USE DATABASE NF26_HOSPITAL;
USE SCHEMA SOC;

CREATE TABLE IF NOT EXISTS R_ROOM (
    ROOM_NUM        INTEGER         NOT NULL,
    ROOM_NAME       VARCHAR(20)     NOT NULL,
    FLOR_NUM        BYTEINT,
    BULD_NAME       VARCHAR(20),
    ROOM_TYP        VARCHAR(10),
    ROOM_DAY_RATE   SMALLINT        NOT NULL,
    CRTN_DT         DATE            NOT NULL,
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (ROOM_NUM)
);

CREATE TABLE IF NOT EXISTS R_MEDC (
    MEDC_ID     INTEGER         NOT NULL,
    MEDC_CD     VARCHAR(10)     NOT NULL,
    MEDC_NAME   VARCHAR(250),
    MEDC_COND   VARCHAR(100),
    MEDC_CATG   VARCHAR(100)    NOT NULL,
    MANF_BRND   VARCHAR(100)    NOT NULL,
    EXEC_ID     INTEGER         NOT NULL        REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (MEDC_ID)
);

CREATE TABLE IF NOT EXISTS R_PART (
    PART_ID     INTEGER         NOT NULL,
    SRC_ID      INTEGER         NOT NULL,
    SRC_TYP     VARCHAR(50)     NOT NULL,
    PRIMARY KEY (PART_ID)
);

CREATE TABLE IF NOT EXISTS O_INDV (
    PART_ID         INTEGER         NOT NULL    REFERENCES R_PART(PART_ID),
    INDV_NAME       VARCHAR(100)    NOT NULL,
    INDV_FIRS_NAME  VARCHAR(100)    NOT NULL,
    INDV_STTS_CD    VARCHAR(10)     NOT NULL,
    CRTN_DTTM       TIMESTAMP(0)    NOT NULL,
    UPDT_DTTM       TIMESTAMP(0)    NOT NULL,
    BIRT_DT         DATE,
    BIRT_CITY       VARCHAR(100),
    BIRT_CNTR       VARCHAR(100),
    SOCL_NUM        VARCHAR(15),
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (PART_ID)
);

CREATE TABLE IF NOT EXISTS O_STFF (
    PART_ID         INTEGER         NOT NULL    REFERENCES R_PART(PART_ID),
    WORK_STRT_DTTM  TIMESTAMP(0)    NOT NULL,
    WORK_END_DTTM   TIMESTAMP(0),
    WORK_END_RESN   VARCHAR(100),
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (PART_ID)
);

CREATE TABLE IF NOT EXISTS O_TELP (
    PART_ID         INTEGER         NOT NULL    REFERENCES R_PART(PART_ID),
    CNTR_IND        VARCHAR(5),
    TELP_NUM        VARCHAR(20)     NOT NULL,
    STRT_VALD_DTTM  TIMESTAMP(0)    NOT NULL,
    END_VALD_DTTM   TIMESTAMP(0)    NOT NULL,
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (PART_ID, STRT_VALD_DTTM)
);

CREATE TABLE IF NOT EXISTS O_ADDR (
    PART_ID         INTEGER         NOT NULL    REFERENCES R_PART(PART_ID),
    STRT_NUM        VARCHAR(10)     NOT NULL,
    STRT_DSC        VARCHAR(250)    NOT NULL,
    COMP_STRT       VARCHAR(250),
    POST_CD         VARCHAR(10)     NOT NULL,
    CITY_NAME       VARCHAR(100),
    CNTR_NAME       VARCHAR(100),
    STRT_VALD_DTTM  TIMESTAMP(0)    NOT NULL,
    END_VALD_DTTM   TIMESTAMP(0)    NOT NULL,
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (PART_ID, STRT_VALD_DTTM)
);

CREATE TABLE IF NOT EXISTS O_CONS (
    CONS_ID         INTEGER         NOT NULL,
    STFF_ID         INTEGER         NOT NULL    REFERENCES O_STFF(PART_ID),
    PATN_ID         INTEGER         NOT NULL    REFERENCES O_INDV(PART_ID),
    CONS_STRT_DTTM  TIMESTAMP(0)    NOT NULL,
    CONS_END_DTTM   TIMESTAMP(0)    NOT NULL,
    PATN_WEGH       FLOAT           NOT NULL, -- FLOAT au lieu de INT pour respecter le STG
    PATN_TEMP       FLOAT, -- idem
    TEMP_UNIT       VARCHAR(15),
    BLD_PRSS        FLOAT, -- idem
    PATH_DSC        VARCHAR(250),
    DIBT_IND        BYTEINT,
    TRET_ID         INTEGER                     REFERENCES R_PART(PART_ID),
    HOSP_IND        BYTEINT,
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (CONS_ID)
);

CREATE TABLE IF NOT EXISTS O_HOSP (
    HOSP_ID         INTEGER         NOT NULL,
    CONS_ID         INTEGER         NOT NULL    REFERENCES O_CONS(CONS_ID),
    ROOM_NUM        INTEGER         NOT NULL    REFERENCES R_ROOM(ROOM_NUM),
    HOSP_STRT_DTTM  TIMESTAMP(0)    NOT NULL,
    HOSP_END_DTTM   TIMESTAMP(0)    NOT NULL,
    HOSP_FINL_RATE  FLOAT           NOT NULL,
    STFF_ID         INTEGER         NOT NULL    REFERENCES O_STFF(PART_ID),
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (HOSP_ID)
);

CREATE TABLE IF NOT EXISTS O_TRET (
    TRET_ID         INTEGER         NOT NULL,
    MEDC_ID         INTEGER                     REFERENCES R_MEDC(MEDC_ID),
    MEDC_QTY        SMALLINT,
    DOSG_DSC        VARCHAR(100)    NOT NULL,
    CONS_ID         INTEGER         NOT NULL    REFERENCES O_CONS(CONS_ID),
    TRET_CRTN_DTTM  TIMESTAMP(0)    NOT NULL,
    EXEC_ID         INTEGER         NOT NULL    REFERENCES TCH.T_SUIV_TRMT(EXEC_ID),
    PRIMARY KEY (TRET_ID)
);
