CREATE TABLE IF NOT EXISTS TCH.PUBLIC.T_SUIV_RUN (
    RUN_ID          INTEGER         NOT NULL,
    RUN_STRT_DTTM   TIMESTAMP(0)    NOT NULL,
    RUN_END_DTTM    TIMESTAMP(0),
    RUN_STTS_CD     VARCHAR(10)     NOT NULL,
    PRIMARY KEY (RUN_ID)
);

CREATE TABLE IF NOT EXISTS TCH.PUBLIC.T_SUIV_TRMT (
    RUN_ID          INTEGER         NOT NULL,
    EXEC_ID         INTEGER         NOT NULL,
    SCRPT_NAME      VARCHAR(250)    NOT NULL,
    EXEC_STRT_DTTM  TIMESTAMP(0)    NOT NULL,
    EXEC_END_DTTM   TIMESTAMP(0),
    EXEC_STTS_CD    VARCHAR(10)     NOT NULL,
    PRIMARY KEY (EXEC_ID)
);
