CREATE TABLE IF NOT EXISTS NF26_HOSPITAL.TCH.T_SUIV_RUN (
    EXEC_ID         CHAR(36)        NOT NULL    REFERENCES NF26_HOSPITAL.TCH.T_SUIV_TRMT(EXEC_ID),
    RUN_STRT_DTTM   TIMESTAMP(0)    NOT NULL,
    RUN_END_DTTM    TIMESTAMP(0),
    RUN_STTS_CD     VARCHAR(10)     NOT NULL,
    PRIMARY KEY (EXEC_ID)
);

CREATE TABLE IF NOT EXISTS NF26_HOSPITAL.TCH.T_SUIV_TRMT (
    EXEC_ID         CHAR(36)        NOT NULL    REFERENCES NF26_HOSPITAL.TCH.T_SUIV_RUN(EXEC_ID),
    SCRPT_NAME      VARCHAR(250)    NOT NULL,
    EXEC_STRT_DTTM  TIMESTAMP(0)    NOT NULL,
    EXEC_END_DTTM   TIMESTAMP(0),
    EXEC_STTS_CD    VARCHAR(10)     NOT NULL,
    PRIMARY KEY (EXEC_ID)
);
