{{
    config(
        materialized='table',
        schema='WRK'
    )
}}

SELECT
    CD_MEDICAMENT       AS MEDC_CD,
    NOM_MEDICAMENT      AS MEDC_NAME,
    CONDIT_MEDICAMENT   AS MEDC_COND,
    CATG_MEDICAMENT     AS MEDC_CATG,
    MARQUE_FABRI        AS MANF_BRND

FROM {{ source('STG', 'MEDICAMENT') }}

WHERE CD_MEDICAMENT IS NOT NULL
  AND CATG_MEDICAMENT IS NOT NULL
  AND MARQUE_FABRI IS NOT NULL
