SELECT
    NO_CHAMBRE      AS ROOM_NUM,
    NOM_CHAMBRE     AS ROOM_NAME,
    NO_ETAGE        AS FLOR_NUM,
    NOM_BATIMENT    AS BULD_NAME,
    TYPE_CHAMBRE    AS ROOM_TYP,
    PRIX_JOUR       AS ROOM_DAY_RATE,
    DT_CREATION     AS CRTN_DT

FROM {{ source('STG', 'CHAMBRE') }}

WHERE NO_CHAMBRE IS NOT NULL
  AND NOM_CHAMBRE IS NOT NULL
  AND PRIX_JOUR IS NOT NULL
  AND DT_CREATION IS NOT NULL
