SELECT
    ID_PERSONNEL        AS SRC_ID,
    FONCTION_PERSONNEL  AS SRC_TYP,
    TS_DEBUT_ACTIVITE   AS WORK_STRT_DTTM,
    TS_FIN_ACTIVITE     AS WORK_END_DTTM,
    RAISON_FIN_ACTIVITE AS WORK_END_RESN

FROM {{ source('STG', 'PERSONNEL') }}

WHERE ID_PERSONNEL IS NOT NULL
  AND FONCTION_PERSONNEL IS NOT NULL
  AND TS_DEBUT_ACTIVITE IS NOT NULL
