SELECT
    ID_HOSPI  AS HOSP_ID,
    ID_CONSULT  AS CONS_ID,
    NO_CHAMBRE  AS ROOM_NUM,
    TS_DEBUT_HOSPI  AS HOSP_STRT_DTTM,
    TS_FIN_HOSPI  AS HOSP_END_DTTM,
    COUT_HOSPI  AS HOSP_FINL_RATE,
    ID_PERSONNEL_RESP  AS STFF_ID

FROM {{ source('STG', 'HOSPITALISATION') }}

WHERE ID_HOSPI IS NOT NULL
  AND ID_CONSULT IS NOT NULL
  AND NO_CHAMBRE IS NOT NULL
  AND TS_DEBUT_HOSPI IS NOT NULL
  AND TS_FIN_HOSPI IS NOT NULL
  AND COUT_HOSPI IS NOT NULL
  AND ID_PERSONNEL_RESP IS NOT NULL