SELECT
    ID_TRAITEMENT           AS TRET_ID,
    CD_MEDICAMENT           AS MEDC_CD,
    CATG_MEDICAMENT         AS MEDC_CATG,
    MARQUE_FABRI            AS MANF_BRND,
    QTE_MEDICAMENT          AS MEDC_QTY,
    DSC_POSOLOGIE           AS DOSG_DSC,
    ID_CONSULT              AS CONS_ID,
    TS_CREATION_TRAITEMENT  AS TRET_CRTN_DTTM

FROM {{ source('STG', 'TRAITEMENT') }}

WHERE ID_TRAITEMENT IS NOT NULL
  AND ID_CONSULT IS NOT NULL
  AND DSC_POSOLOGIE IS NOT NULL
