SELECT
    ID_PATIENT          AS SRC_ID,
    IND_PAYS_NUM_TELP   AS CNTR_IND,
    NUM_TELEPHONE       AS TELP_NUM,
    TS_CREATION_PATIENT AS STRT_VALD_DTTM,
    TS_MAJ_PATIENT      AS END_VALD_DTTM

FROM {{ source('STG', 'PATIENT') }}

WHERE ID_PATIENT            IS NOT NULL
  AND NUM_TELEPHONE         IS NOT NULL
  AND TS_CREATION_PATIENT   IS NOT NULL
  AND TS_MAJ_PATIENT        IS NOT NULL