-- Personnel
SELECT
    ID_PERSONNEL        AS SRC_ID,
    FONCTION_PERSONNEL  AS SRC_TYP,
    NOM_PERSONNEL       AS INDV_NAME,
    PRENOM_PERSONNEL    AS INDV_FIRS_NAME,
    CD_STATUT_PERSONNEL AS INDV_STTS_CD,
    TS_CREATION_PERSONNEL AS CRTN_DTTM,
    TS_MAJ_PERSONNEL    AS UPDT_DTTM,
    NULL::DATE          AS BIRT_DT,
    NULL::VARCHAR(100)  AS BIRT_CITY,
    NULL::VARCHAR(100)  AS BIRT_CNTR,
    NULL::VARCHAR(15)   AS SOCL_NUM

FROM {{ source('STG', 'PERSONNEL') }}

WHERE ID_PERSONNEL IS NOT NULL
  AND FONCTION_PERSONNEL IS NOT NULL
  AND NOM_PERSONNEL IS NOT NULL
  AND PRENOM_PERSONNEL IS NOT NULL

UNION

-- Patients
SELECT
    ID_PATIENT          AS SRC_ID,
    'Patient'           AS SRC_TYP,
    NOM_PATIENT         AS INDV_NAME,
    PRENOM_PATIENT      AS INDV_FIRS_NAME,
    'Actif'             AS INDV_STTS_CD,
    TS_CREATION_PATIENT AS CRTN_DTTM,
    TS_MAJ_PATIENT      AS UPDT_DTTM,
    DT_NAISS            AS BIRT_DT,
    VILLE_NAISS         AS BIRT_CITY,
    PAYS_NAISS          AS BIRT_CNTR,
    NUM_SECU            AS SOCL_NUM

FROM {{ source('STG', 'PATIENT') }}

WHERE ID_PATIENT IS NOT NULL
  AND NOM_PATIENT IS NOT NULL
  AND PRENOM_PATIENT IS NOT NULL
