SELECT
    ID_CONSULT              AS CONS_ID,
    ID_PERSONNEL            AS STFF_ID,
    ID_PATIENT              AS PATN_ID,
    TS_DEBUT_CONSULT        AS CONS_STRT_DTTM,
    TS_FIN_CONSULT          AS CONS_END_DTTM,
    POIDS_PATIENT           AS PATN_WEGH,
    TEMP_PATIENT            AS PATN_TEMP,
    UNIT_TEMP               AS TEMP_UNIT,
    TENSION_PATIENT         AS BLD_PRSS,
    DSC_PATHO               AS PATH_DSC,
    CASE INDIC_DIABETE
    WHEN 'True'  THEN 1
    WHEN 'False' THEN 0
    ELSE NULL
END                     AS DIBT_IND,
    ID_TRAITEMENT           AS TRET_ID,
    CASE INDIC_HOSPI
        WHEN 'True' THEN 1
        WHEN 'False' THEN 0
        ELSE NULL
    END                     AS HOSP_IND

FROM {{ source('STG', 'CONSULTATION') }}

WHERE ID_CONSULT IS NOT NULL
  AND ID_PERSONNEL IS NOT NULL
  AND ID_PATIENT IS NOT NULL
  AND TS_DEBUT_CONSULT IS NOT NULL
  AND TS_FIN_CONSULT IS NOT NULL
  AND POIDS_PATIENT IS NOT NULL